services:
  mysql:
    image: mysql:8.4
    container_name: seckill-mysql
    environment:
      MYSQL_ROOT_PASSWORD: seckill
      MYSQL_DATABASE: seckill
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  redis:
    image: redis:7.4
    container_name: seckill-redis
    ports:
      - "6379:6379"

  # 本地联调参考：生产以 K8s infra/k8s/12-rocketmq.yaml 为准
  rocketmq-namesrv:
    image: apache/rocketmq:5.1.4
    container_name: seckill-rocketmq-namesrv
    command: ["sh", "mqnamesrv"]
    environment:
      JAVA_OPT_EXT: "-Xms256m -Xmx256m"
    ports:
      - "9876:9876"

  rocketmq-broker:
    image: apache/rocketmq:5.1.4
    container_name: seckill-rocketmq-broker
    depends_on:
      - rocketmq-namesrv
    command:
      - sh
      - mqbroker
      - -n
      - rocketmq-namesrv:9876
      - -c
      - /home/rocketmq/rocketmq-5.1.4/conf/broker.conf
    environment:
      JAVA_OPT_EXT: "-Xms256m -Xmx512m"
      NAMESRV_ADDR: rocketmq-namesrv:9876
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"

volumes:
  mysql-data:
